In [1]:
# KNN on income dataset
#To visualize the data
import seaborn as sns
#To work with dataframes
import pandas as pd
#To perform numerical operations
import numpy as np
#To partition the data
from sklearn.model_selection import train_test_split
#importing the library for logistic regression
from sklearn.linear_model import LogisticRegression
#importing performance metrics
from sklearn.metrics import accuracy_score,confusion_matrix



In [2]:
"""
Data encoding
the salary status categories are encoded as 0,1
"""
#importing data
data=pd.read_csv(r"C:\Users\Gnaneshwari\Desktop\income.csv",na_values=[" ?"])
data2=data.dropna(axis=0) 
#Optimization of model by removing uncessary variables
#Regression - remove insignificant variables
cat_salStat={" less than or equal to 50,000":0,
             " greater than 50,000":1}
data2["SalStat"].replace(cat_salStat,inplace=True)
print(data2["SalStat"].head(6))



0    0
1    0
2    1
3    0
4    0
5    0
Name: SalStat, dtype: int64


C:\Users\Gnaneshwari\AppData\Local\Temp\ipykernel_18168\1477848826.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["SalStat"].replace(cat_salStat,inplace=True)


In [3]:
cols=["gender","nativecountry","race","JobType"]
new_data=data2.drop(cols,axis=1,inplace=True)
new_data=pd.get_dummies(data2,drop_first=True)
#storing the column names
column_list=list(new_data.columns)
print(column_list)


['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-serv', 'occupation_ Sales', 'occupation_ Tech-support', 'occupation_ Transport-moving', 'relationship_ Not-in-family', 'relationship_ Other-rel

C:\Users\Gnaneshwari\AppData\Local\Temp\ipykernel_18168\600739918.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data=data2.drop(cols,axis=1,inplace=True)


In [4]:
#seperating input features from the data
features=list(set(column_list)-set(["SalStat"]))
print(features)
#Storing output variable values in y
y=new_data["SalStat"].values
print(y)
#storing input feature values in x
x=new_data[features].values
print(x)

#splitting the data into train and test
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,
                                               random_state=0)




['EdType_ Prof-school', 'EdType_ HS-grad', 'occupation_ Exec-managerial', 'maritalstatus_ Married-civ-spouse', 'capitalgain', 'EdType_ 1st-4th', 'relationship_ Wife', 'maritalstatus_ Widowed', 'maritalstatus_ Married-AF-spouse', 'relationship_ Own-child', 'EdType_ 9th', 'occupation_ Handlers-cleaners', 'occupation_ Craft-repair', 'EdType_ Assoc-acdm', 'hoursperweek', 'occupation_ Machine-op-inspct', 'EdType_ Doctorate', 'age', 'occupation_ Tech-support', 'EdType_ 11th', 'occupation_ Sales', 'EdType_ Masters', 'EdType_ Preschool', 'maritalstatus_ Never-married', 'occupation_ Armed-Forces', 'occupation_ Other-service', 'occupation_ Farming-fishing', 'EdType_ Assoc-voc', 'EdType_ Some-college', 'occupation_ Protective-serv', 'EdType_ 12th', 'maritalstatus_ Separated', 'capitalloss', 'EdType_ 7th-8th', 'relationship_ Not-in-family', 'maritalstatus_ Married-spouse-absent', 'EdType_ 5th-6th', 'occupation_ Priv-house-serv', 'EdType_ Bachelors', 'relationship_ Unmarried', 'occupation_ Prof-spe

In [5]:
train_x,test_x,train_y,test_y

(array([[False, False, False, ..., False, True, False],
        [False, True, False, ..., False, False, False],
        [False, True, False, ..., False, True, False],
        ...,
        [False, False, False, ..., True, False, False],
        [False, True, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]], dtype=object),
 array([[False, True, False, ..., False, False, False],
        [False, False, False, ..., True, False, False],
        [False, False, True, ..., False, False, False],
        ...,
        [False, False, False, ..., True, False, False],
        [False, True, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]], dtype=object),
 array([0, 0, 0, ..., 1, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [6]:
#%%
#KNN
#importing the library of KNN
from sklearn.neighbors import KNeighborsClassifier
#importing matplotlib library
import matplotlib.pyplot as plt
#%%



In [ ]:
pip install --user scikit-learn


In [ ]:
pip install --upgrade scikit-learn numpy threadpoolctl


In [7]:
#storing the K-nearest neighbors classifiers
KNN_classifier=KNeighborsClassifier(n_neighbors=5)
#model building
KNN_classifier.fit(train_x,train_y)

#predicting the test values with model
prediction=KNN_classifier.predict(test_x)
print(prediction)



[0 0 0 ... 0 0 0]


In [8]:
#evaluating the model
print("performance")
conf_matrix=confusion_matrix(test_y,prediction)
print(conf_matrix)

#calculating accuracy
acc_score=accuracy_score(test_y,prediction)
print("accuracy score")
print(acc_score)

#miss classified
print("miss classified")
print((test_y!=prediction).sum())



performance
[[6187  636]
 [ 862 1364]]
accuracy score
0.8344568460603382
miss classified
1498


In [9]:
#Effect of k value on classifier
miss_classified=[]
for k in range(1,20):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(train_x,train_y)
    pred_k=knn.predict(test_x)
    miss_classified.append((test_y!=pred_k).sum())
print("Miss classified")
print(miss_classified)



Miss classified
[1723, 1512, 1544, 1469, 1498, 1443, 1469, 1456, 1464, 1430, 1476, 1456, 1457, 1451, 1455, 1442, 1436, 1425, 1444]
